LOGIN = 'login'

# Search view
FIRST_JOB = 'UW_CO_JOBTITLE_HL$span$0'
SEARCH_BUTTON = 'UW_CO_JOBSRCHDW_UW_CO_DW_SRCHBTN'
JOB_ID_GENERIC = 'UW_CO_JOBRES_VW_UW_CO_JOB_ID'
NEXT_PAGE_BUTTON = 'UW_CO_JOBRES_VW$fdown$0'

TERM_ID = 'UW_CO_JOBSRCH_UW_CO_WT_SESSION'
EMPLOYER_NAME = 'UW_CO_JOBSRCH_UW_CO_EMPLYR_NAME'
JOB_TITLE = 'UW_CO_JOBSRCH_UW_CO_JOB_TITLE'

LEVEL_JUNIOR = 'UW_CO_JOBSRCH_UW_CO_COOP_JR'
LEVEL_INTERMEDIATE = 'UW_CO_JOBSRCH_UW_CO_COOP_INT'
LEVEL_SENIOR = 'UW_CO_JOBSRCH_UW_CO_COOP_SR'

# Job profile view
POSTING_OPEN_DATE = 'UW_CO_JOBDTL_VW_UW_CO_CHAR_EDATE'
LAST_DAY_TO_APPLY = 'UW_CO_JOBDTL_VW_UW_CO_CHAR_DATE'
EMPLOYER_JOB_NUMBER = 'UW_CO_JOBDTL_VW_UW_CO_EMPOWN_JOBNO'
EMPLOYER = 'UW_CO_JOBDTL_DW_UW_CO_EMPUNITDIV'
JOB_TITLE = 'UW_CO_JOBDTL_VW_UW_CO_JOB_TITLE'
WORK_LOCATION = 'UW_CO_JOBDTL_VW_UW_CO_WORK_LOCATN'
GRADES = 'UW_CO_JOBDTL_DW_UW_CO_MARKS_DRVD'
AVAILABLE_OPENINGS = 'UW_CO_JOBDTL_VW_UW_CO_AVAIL_OPENGS'
DISCIPLINES = 'UW_CO_JOBDTL_DW_UW_CO_DESCR'
DISCIPLINES_MORE = 'UW_CO_JOBDTL_DW_UW_CO_DESCR100'
LEVELS = 'UW_CO_JOBDTL_DW_UW_CO_DESCR_100'
HIRING_PROCESS_SUPPORT = 'UW_CO_OD_DV2_UW_CO_NAME'
WORK_TERM_SUPPORT = 'UW_CO_OD_DV2_UW_CO_NAME2'
COMMENTS = 'UW_CO_JOBDTL_VW_UW_CO_JOB_SUMMARY'
JOB_DESCRIPTION = 'UW_CO_JOBDTL_VW_UW_CO_JOB_DESCR'
