LOGIN = 'login'

# Search
NUM_APPS_REMAINING = 'UW_CO_JOBSRCHDW_UW_CO_MAX_NUM_APPL'

FIRST_JOB = 'UW_CO_JOBTITLE_HL$span$0'
SEARCH_BUTTON = 'UW_CO_JOBSRCHDW_UW_CO_DW_SRCHBTN'
NEXT_PAGE_BUTTON = 'UW_CO_JOBRES_VW$fdown$0'

SEARCH_TERM_ID = 'UW_CO_JOBSRCH_UW_CO_WT_SESSION'
SEARCH_EMPLOYER_NAME = 'UW_CO_JOBSRCH_UW_CO_EMPLYR_NAME'
SEARCH_JOB_TITLE = 'UW_CO_JOBSRCH_UW_CO_JOB_TITLE'
SEARCH_LOCATION = 'UW_CO_JOBSRCH_UW_CO_LOCATION'

LEVEL_JUNIOR = 'UW_CO_JOBSRCH_UW_CO_COOP_JR'
LEVEL_INTERMEDIATE = 'UW_CO_JOBSRCH_UW_CO_COOP_INT'
LEVEL_SENIOR = 'UW_CO_JOBSRCH_UW_CO_COOP_SR'
LEVEL_BACHELOR = 'UW_CO_JOBSRCH_UW_CO_BACHELOR'
LEVEL_MASTERS = 'UW_CO_JOBSRCH_UW_CO_MASTERS'
LEVEL_PHD = 'UW_CO_JOBSRCH_UW_CO_PHD'

# Job listing
JOB_LISTING_COLUMNS = [
	'UW_CO_JOBRES_VW_UW_CO_JOB_ID',
	'UW_CO_JOBTITLE_HL$span',
	'UW_CO_JOBRES_VW_UW_CO_PARENT_NAME',
	'UW_CO_JOBRES_VW_UW_CO_EMPLYR_NAME1',
	'UW_CO_JOBRES_VW_UW_CO_WORK_LOCATN',
	'UW_CO_JOBRES_VW_UW_CO_OPENGS',
	'UW_CO_APPLY_HL$span',
	'UW_CO_JOBAPP_CT_UW_CO_MAX_RESUMES',
	'UW_CO_JOBRES_VW_UW_CO_CHAR_DATE'
]

# Job profile view
PROFILE_POSTING_OPEN_DATE = 'UW_CO_JOBDTL_VW_UW_CO_CHAR_EDATE'
PROFILE_LAST_DAY_TO_APPLY = 'UW_CO_JOBDTL_VW_UW_CO_CHAR_DATE'
PROFILE_EMPLOYER_JOB_NUMBER = 'UW_CO_JOBDTL_VW_UW_CO_EMPOWN_JOBNO'
PROFILE_EMPLOYER = 'UW_CO_JOBDTL_DW_UW_CO_EMPUNITDIV'
PROFILE_JOB_TITLE = 'UW_CO_JOBDTL_VW_UW_CO_JOB_TITLE'
PROFILE_WORK_LOCATION = 'UW_CO_JOBDTL_VW_UW_CO_WORK_LOCATN'
PROFILE_GRADES = 'UW_CO_JOBDTL_DW_UW_CO_MARKS_DRVD'
PROFILE_AVAILABLE_OPENINGS = 'UW_CO_JOBDTL_VW_UW_CO_AVAIL_OPENGS'
PROFILE_DISCIPLINES = 'UW_CO_JOBDTL_DW_UW_CO_DESCR'
PROFILE_DISCIPLINES_MORE = 'UW_CO_JOBDTL_DW_UW_CO_DESCR100'
PROFILE_LEVELS = 'UW_CO_JOBDTL_DW_UW_CO_DESCR_100'
PROFILE_HIRING_PROCESS_SUPPORT = 'UW_CO_OD_DV2_UW_CO_NAME'
PROFILE_WORK_TERM_SUPPORT = 'UW_CO_OD_DV2_UW_CO_NAME2'
PROFILE_COMMENTS = 'UW_CO_JOBDTL_VW_UW_CO_JOB_SUMMARY'
PROFILE_JOB_DESCRIPTION = 'UW_CO_JOBDTL_VW_UW_CO_JOB_DESCR'

