AFRICA = 'Africa'
AFRICA_GHANA = 'Africa > Ghana'
AFRICA_KENYA = 'Africa > Kenya'
AFRICA_NIGERIA = 'Africa > Nigeria'
AFRICA_RWANDA = 'Africa > Rwanda'

ASIA = 'Asia'
ASIA_INDIA = 'Asia > India'
ASIA_PAKISTAN = 'Asia > Pakistan'
ASIA_PHILIPPINES = 'Asia > Philippines'

AUSTRALIA_NEW_ZEALAND = 'Australia/New Zealand'

CANADA = 'Canada'
CANADA_EASTERN = 'Canada > Eastern Canada'
CANADA_NATIONAL_CAPITAL_REGION = 'Canada > National Capital Region'
CANADA_NORTHERN = 'Canada > Northern Canada'
CANADA_ONTARIO = 'Canada > Ontario'
CANADA_ONTARIO_CENTRAL = 'Canada > Ontario > Central Ontario'
CANADA_ONTARIO_EASTERN = 'Canada > Ontario > Eastern Ontario'
CANADA_ONTARIO_GTA = 'Canada > Ontario > GTA'
CANADA_ONTARIO_GTA_CENTRAL_EAST = 'Canada > Ontario > GTA > Central East'
CANADA_ONTARIO_GTA_CENTRAL_WEST = 'Canada > Ontario > GTA > GTA Central West'
CANADA_ONTARIO_GTA_NORTH = 'Canada > Ontario > GTA > GTA North'
CANADA_ONTARIO_GTA_TORONTO = 'Canada > Ontario > GTA > Toronto'
CANADA_ONTARIO_GTA_TORONTO_DOWNTOWN = 'Canada > Ontario > GTA > Toronto > Toronto Downtown'
CANADA_ONTARIO_HAMILTON_NIAGARA_REGION = 'Canada > Ontario > Hamilton/Niagara Region'
CANADA_ONTARIO_NORTHERN = 'Canada > Ontario > Northern Ontario'
CANADA_ONTARIO_SOUTH_WEST = 'Canada > Ontario > South-West Ontario'
CANADA_ONTARIO_SOUTH_WEST_BRANTFORD_REGION = 'Canada > Ontario > South-West Ontario > Brantford Region'
CANADA_ONTARIO_SOUTH_WEST_GREY_BRUCE_REGION = 'Canada > Ontario > South-West Ontario > Grey Bruce Region'
CANADA_ONTARIO_SOUTH_WEST_GUELPH_REGION = 'Canada > Ontario > South-West Ontario > Guelph Region'
CANADA_ONTARIO_SOUTH_WEST_LONDON_REGION = 'Canada > Ontario > South-West Ontario > London Region'
CANADA_ONTARIO_SOUTH_WEST_SARNIA_REGION = 'Canada > Ontario > South-West Ontario > Sarnia Region'
CANADA_ONTARIO_SOUTH_WEST_WATERLOO_REGION = 'Canada > Ontario > South-West Ontario > Waterloo Region'
CANADA_ONTARIO_SOUTH_WEST_WINDSOR_REGION = 'Canada > Ontario > South-West Ontario > Windsor Region'
CANADA_QUEBEC = 'Canada > Quebec'
CANADA_QUEBEC_MONTREAL_REGION = 'Canada > Quebec > Montreal Region'
CANADA_WESTERN = 'Canada > Western Canada'

CARIBBEAN_SOUTH_AMERICA = 'Caribbean/South America'

CENTRAL_AMERICA = 'Central America'

EUROPE = 'Europe'

MEXICO = 'Mexico'

MIDDLE_EAST = 'Middle East'
MIDDLE_EAST_IRAN = 'Middle East > Iran'
MIDDLE_EAST_OMAN = 'Middle East > Oman'
MIDDLE_EAST_QATAR = 'Middle East > Qatar'
MIDDLE_EAST_ARABIA = 'Middle East > Saudi Arabia'
MIDDLE_EAST_UAE = 'Middle East > UAE'

UNITED_STATES = 'United States'

