BASE = 'https://jobmine.ccol.uwaterloo.ca/'

SEARCH = BASE + 'psc/SS/EMPLOYEE/WORK/c/UW_CO_STUDENTS.UW_CO_JOBSRCH'
LOGIN = BASE + 'psp/SS/EMPLOYEE/WORK/'
JOB_PROFILE = BASE + 'psc/SS_2/EMPLOYEE/WORK/c/UW_CO_STUDENTS.UW_CO_JOBDTLS.GBL?UW_CO_JOB_ID='
